image: node:10

stages:
  - .pre
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

install:
  stage: .pre
  script:
    - npm i

test:
  stage: test
  script:
    - npm run test

lint:
  stage: test
  script:
    - npm run lint
  artifacts:
    paths:
      - ./junit
    reports:
      junit: ./junit/*lint.xml

build:
  stage: build
  script:
    - npm run zip
  artifacts:
    expire_in: 1 day
    paths:
      - dist/

deploy_prod:
  stage: deploy
  script:
    - npm run deploy
  environment:
    name: production
  when: manual
  only:
    - master